fix(ci): use nightly clippy
Required if we want to use `#![feature(...)]`s, else clippy complains:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/lib.rs:18:1
   |
18 | #![feature(naked_functions)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `esp-riscv-rt` due to previous error
Error: Process completed with exit code 101.
```